package com.example.mycrm.model.organization;

public enum BusinessEventType {
    PERSON_HIRED,
    PERSON_FIRED,
    PERSON_MOVED_TO_NEW_POSITION,
    CONTACT_INCOMING,
    CONTACT_OUTGOING,
    MEETING,
    MESSAGE_INCOMING,
    MESSAGE_OUTGOING,
    INQUIRY_RECEIVED,
    PROPOSAL_SENT,
    PROPOSAL_ACCEPTED,
    ORDER_RECEIVED,
    INVOICED_SENT,
    PAYMENT_RECEIVED,
    GOODS_SHIPPED_OUT
}
